services:
  hello-world:
    container_name: hello-world
    image: crccheck/hello-world
    labels:
      - traefik.enable=true

      - traefik.http.routers.hello-world-http.entrypoints=web
      - traefik.http.routers.hello-world-http.rule=Host(`localhost`)
      # crccheck/hello-world is served on port 8000 by default
      - traefik.http.services.hello-world-http.loadbalancer.server.port=8000

      - traefik.http.routers.hello-world-https.entrypoints=websecure
      - traefik.http.routers.hello-world-https.rule=Host(`localhost`)
      - traefik.http.routers.hello-world-https.tls=true
      - traefik.http.routers.hello-world-https.tls.certresolver=letsencrypt
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true
