services:
  hello-world:
    container_name: hello-world
    image: crccheck/hello-world
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello-world.entrypoints=web
      - traefik.http.routers.hello-world.rule=Host(`localhost`)
      - traefik.http.services.hello-world.loadbalancer.server.port=8000
    ports:
      - "8000:8000"
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true
