services:
  traefik:
    container_name: "traefik"
    image: "traefik:latest"
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

networks:
  traefik-network:
    external: true
